name: Auto reviewer assign for depandabot

on:
  pull_request:
    types: opened

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'dependabot')
    steps:
      - name: Set reviewers
        env:
          REVIEWERS: "ShuheiYoshino" # edit here
        run: |
          # "hoge, fuga, piyo" を ["hoge", "fuga", "piyo"]に変換
          reviewers=$(echo "\"${REVIEWERS// /}\"" | jq 'split(",")')
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"reviewers\": $reviewers }" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers